server:
  port: 8082
  mode: "dev"
postgresql:
  host: 127.0.0.1
  port: 33306
  username: postgres
  password: anhiuemlove33
  db_name: booking_movie_ticket
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600