server:
  port: 8082
  mode: "dev"
postgresql:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: anhiuemlove33
  db_name: booking_movie_ticket
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true